"use client";

import { useState } from "react";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import MenuItem from "@mui/material/MenuItem";
import Paper from "@mui/material/Paper";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import useMediaQuery from "@mui/material/useMediaQuery";
import { useTheme } from "@mui/material/styles";
import type { ImpactArea, ImpactEntity } from "@/lib/emotional-context";
import { contextRequest } from "./context-api";

type Draft = { type: "area" | "entity"; id?: string; name: string; color: string; areaId: string };

export function ImpactManager({ initialAreas, initialEntities }: { initialAreas: ImpactArea[]; initialEntities: ImpactEntity[] }) {
  const compact = useMediaQuery(useTheme().breakpoints.down("sm"));
  const [areas, setAreas] = useState(initialAreas); const [entities, setEntities] = useState(initialEntities);
  const [draft, setDraft] = useState<Draft | null>(null); const [pendingDelete, setPendingDelete] = useState<Draft | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function reload() { const response = await fetch("/api/context/impacts"); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Could not load impact library."); setAreas(result.areas); setEntities(result.entities); }
  async function run(task: () => Promise<unknown>) { setBusy(true); setError(""); try { await task(); await reload(); return true; } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save impact library."); return false; } finally { setBusy(false); } }
  async function save() { if (!draft?.name.trim()) return; const current = draft; if (await run(() => current.type === "area" ? current.id ? contextRequest(`/api/context/areas/${current.id}`, "PATCH", { name: current.name, color: current.color }) : contextRequest("/api/context/areas", "POST", { name: current.name, color: current.color }) : current.id ? contextRequest(`/api/context/entities/${current.id}`, "PATCH", { name: current.name, areaId: current.areaId }) : contextRequest("/api/context/entities", "POST", { name: current.name, areaId: current.areaId }))) setDraft(null); }
  async function moveArea(area: ImpactArea, direction: -1 | 1) { const ordered = areas.filter(item => !item.archived_at).sort((a, b) => a.position - b.position || a.name.localeCompare(b.name)); const index = ordered.findIndex(item => item.id === area.id); const next = index + direction; if (next < 0 || next >= ordered.length) return; [ordered[index], ordered[next]] = [ordered[next], ordered[index]]; await run(async () => { for (const [position, item] of ordered.entries()) await contextRequest(`/api/context/areas/${item.id}`, "PATCH", { position }); }); }
  async function moveEntity(entity: ImpactEntity, direction: -1 | 1) { const ordered = entities.filter(item => item.area_id === entity.area_id && !item.archived_at).sort((a, b) => a.position - b.position || a.name.localeCompare(b.name)); const index = ordered.findIndex(item => item.id === entity.id); const next = index + direction; if (next < 0 || next >= ordered.length) return; [ordered[index], ordered[next]] = [ordered[next], ordered[index]]; await run(async () => { for (const [position, item] of ordered.entries()) await contextRequest(`/api/context/entities/${item.id}`, "PATCH", { position }); }); }
  return <Stack className="context-manager" spacing={2}>
    <Typography color="text.secondary">Impact areas are broad parts of life. Entities are specific people, projects, habits, or other things within an area. Archived items stay readable in past entries.</Typography>
    <Button variant="contained" sx={{ alignSelf: "flex-start" }} onClick={() => setDraft({ type: "area", name: "", color: "#7A8291", areaId: "" })}>Create impact area</Button>
    {error && <Alert severity="error" role="alert">{error}</Alert>}
    {[...areas].sort((a, b) => a.position - b.position || a.name.localeCompare(b.name)).map(area => <Paper component="section" key={area.id} variant="outlined" sx={{ p: { xs: 2, sm: 3 } }} aria-label={area.name}><Stack spacing={2}><Stack direction={{ xs: "column", md: "row" }} sx={{ justifyContent: "space-between", alignItems: { md: "center" }, gap: 1 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><Box sx={{ width: 14, height: 14, borderRadius: "50%", bgcolor: area.color, border: 1, borderColor: "divider" }}/><Typography variant="h2">{area.name}</Typography>{area.archived_at && <Chip size="small" label="Archived"/>}</Stack><Stack direction="row" sx={{ flexWrap: "wrap", gap: 0.5 }}><Button size="small" onClick={() => setDraft({ type: "area", id: area.id, name: area.name, color: area.color, areaId: "" })}>Edit</Button><Button size="small" aria-label={`Move ${area.name} up`} disabled={busy} onClick={() => void moveArea(area, -1)}>↑</Button><Button size="small" aria-label={`Move ${area.name} down`} disabled={busy} onClick={() => void moveArea(area, 1)}>↓</Button><Button size="small" disabled={busy} onClick={() => void run(() => contextRequest(`/api/context/areas/${area.id}`, "PATCH", { archived: !area.archived_at }))}>{area.archived_at ? "Restore" : "Archive"}</Button><Button size="small" color="error" onClick={() => setPendingDelete({ type: "area", id: area.id, name: area.name, color: area.color, areaId: "" })}>Delete</Button></Stack></Stack>
    <Stack spacing={1}>{entities.filter(item => item.area_id === area.id).sort((a, b) => a.position - b.position || a.name.localeCompare(b.name)).map(entity => <Stack key={entity.id} direction={{ xs: "column", sm: "row" }} sx={{ alignItems: { sm: "center" }, justifyContent: "space-between", gap: 1, pl: { sm: 2 }, borderTop: 1, borderColor: "divider", pt: 1 }}><Stack direction="row" spacing={1} sx={{ alignItems: "center" }}><Typography>↳ {entity.name}</Typography>{entity.archived_at && <Chip size="small" label="Archived"/>}</Stack><Stack direction="row" sx={{ flexWrap: "wrap", gap: 0.5 }}><Button size="small" onClick={() => setDraft({ type: "entity", id: entity.id, name: entity.name, color: area.color, areaId: area.id })}>Edit</Button><Button size="small" aria-label={`Move ${entity.name} up`} disabled={busy} onClick={() => void moveEntity(entity, -1)}>↑</Button><Button size="small" aria-label={`Move ${entity.name} down`} disabled={busy} onClick={() => void moveEntity(entity, 1)}>↓</Button><Button size="small" disabled={busy} onClick={() => void run(() => contextRequest(`/api/context/entities/${entity.id}`, "PATCH", { archived: !entity.archived_at }))}>{entity.archived_at ? "Restore" : "Archive"}</Button><Button size="small" color="error" onClick={() => setPendingDelete({ type: "entity", id: entity.id, name: entity.name, color: area.color, areaId: area.id })}>Delete</Button></Stack></Stack>)}</Stack>
    {!area.archived_at && <Button variant="outlined" sx={{ alignSelf: "flex-start" }} onClick={() => setDraft({ type: "entity", name: "", color: area.color, areaId: area.id })}>Add entity to {area.name}</Button>}
    </Stack></Paper>)}
    {areas.length === 0 && <Paper variant="outlined" sx={{ p: 3 }}><Typography color="text.secondary">No impact areas yet. Create one for a part of life you want to reflect on.</Typography></Paper>}
    <Dialog open={Boolean(draft)} onClose={() => setDraft(null)} fullWidth maxWidth="sm" fullScreen={compact} aria-labelledby="impact-edit-title"><DialogTitle id="impact-edit-title">{draft?.id ? "Edit" : "Create"} {draft?.type === "entity" ? "entity" : "impact area"}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><TextField label="Name" value={draft?.name || ""} onChange={event => setDraft(current => current && { ...current, name: event.target.value })} slotProps={{ htmlInput: { maxLength: 80 } }} required fullWidth/>{draft?.type === "area" ? <label>Color <input type="color" value={draft.color} onChange={event => setDraft(current => current && { ...current, color: event.target.value })}/></label> : <TextField select label="Impact area" value={draft?.areaId || ""} onChange={event => setDraft(current => current && { ...current, areaId: event.target.value })} fullWidth>{areas.filter(item => !item.archived_at).map(item => <MenuItem key={item.id} value={item.id}>{item.name}</MenuItem>)}</TextField>}{error && <Alert severity="error" role="alert">{error}</Alert>}</Stack></DialogContent><DialogActions><Button onClick={() => setDraft(null)}>Cancel</Button><Button variant="contained" disabled={busy || !draft?.name.trim() || (draft?.type === "entity" && !draft.areaId)} onClick={() => void save()}>Save</Button></DialogActions></Dialog>
    <Dialog open={Boolean(pendingDelete)} onClose={() => setPendingDelete(null)} aria-labelledby="impact-delete-title"><DialogTitle id="impact-delete-title">Delete {pendingDelete?.name}?</DialogTitle><DialogContent>Items used in journal sections will be archived so older entries remain understandable.</DialogContent><DialogActions><Button onClick={() => setPendingDelete(null)}>Cancel</Button><Button variant="contained" color="error" disabled={busy} onClick={() => void run(async () => { await contextRequest(`/api/context/${pendingDelete?.type === "area" ? "areas" : "entities"}/${pendingDelete?.id}`, "DELETE"); setPendingDelete(null); })}>Delete or archive</Button></DialogActions></Dialog>
  </Stack>;
}
