"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import Link from "next/link";
type Journal = { id: string; name: string; description: string | null; color: string; archived_at: string | null; position: number };
const colors = ["#a88767", "#6e8b75", "#6a7d9c", "#ba8390", "#bc9b55", "#7c7194"];
export function JournalManager({ journals }: { journals: Journal[] }) {
  const router = useRouter(); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [color, setColor] = useState(colors[0]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function create(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const response = await fetch("/api/journals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, description, color }) }); if (!response.ok) throw new Error("Could not create journal."); setName(""); setDescription(""); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create journal."); } finally { setBusy(false); } }
  async function update(id: string, patch: Record<string, unknown>) { const response = await fetch(`/api/journals/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); if (response.ok) router.refresh(); else setError("Could not update journal."); }
  async function remove(id: string) { if (!confirm("Delete this empty journal?")) return; const response = await fetch(`/api/journals/${id}`, { method: "DELETE" }); if (response.ok) router.refresh(); else { const data = await response.json(); setError(data.error || "Could not delete journal."); } }
  return <><form className="panel stack" onSubmit={create} style={{ marginBottom: 28 }}><h2 style={{ margin: 0 }}>A home for your stories</h2><div className="row" style={{ alignItems: "end", flexWrap: "wrap" }}><label style={{ flex: 2, minWidth: 160 }}>Name<input value={name} onChange={event => setName(event.target.value)} placeholder="Personal, Travel, Ideas…" required maxLength={100} /></label><label style={{ flex: 3, minWidth: 180 }}>Description <small className="muted">Optional</small><input value={description} onChange={event => setDescription(event.target.value)} maxLength={500} placeholder="What belongs here?" /></label><button className="button primary" disabled={busy}>Create journal</button></div><div className="row">{colors.map(value => <button key={value} type="button" aria-label={`Color ${value}`} aria-pressed={color === value} onClick={() => setColor(value)} style={{ width: 26, height: 26, borderRadius: "50%", background: value, border: color === value ? "3px solid #25372a" : "2px solid white", boxShadow: "0 0 0 1px #bbb" }} />)}</div></form>{error && <p role="alert" className="form-message">{error}</p>}<div className="journal-grid">{journals.map((journal, index) => <article key={journal.id} className="journal-card"><div className="between"><span className="journal-dot" style={{ background: journal.color }} /><button className="text-button" onClick={() => { const next = prompt("Journal name", journal.name); if (next?.trim()) void update(journal.id, { name: next.trim() }); }}>Edit</button></div><Link href={`/journals/${journal.id}`}><h2>{journal.name}</h2><p>{journal.description || "A space for what matters."}</p></Link><div className="between"><Link className="text-button" href={`/journals/${journal.id}`}>View entries →</Link><button className="text-button" onClick={() => void update(journal.id, { archived: !journal.archived_at })}>{journal.archived_at ? "Restore" : "Archive"}</button></div><div className="row"><button className="text-button" disabled={index === 0} onClick={() => void update(journal.id, { position: journals[index - 1].position - 1 })}>↑ Earlier</button><button className="text-button" disabled={index === journals.length - 1} onClick={() => void update(journal.id, { position: journals[index + 1].position + 1 })}>↓ Later</button><button className="text-button" onClick={() => void remove(journal.id)}>Delete</button></div></article>)}</div></>;
}
