"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useEffect, useState } from "react";
type Prompt = { id: string; text: string };
type Trashed = { id: string; title: string; local_date: string };
export function SettingsPanel({ email, prompts, trashed }: { email: string; prompts: Prompt[]; trashed: Trashed[] }) { const router = useRouter(); const [theme, setTheme] = useState("system"); const [prompt, setPrompt] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const task = setTimeout(() => setTheme(localStorage.getItem("stillroom-theme") || "system"), 0); return () => clearTimeout(task); }, []);
  function chooseTheme(value: string) { setTheme(value); localStorage.setItem("stillroom-theme", value); document.documentElement.dataset.theme = value; }
  async function signOut() { await fetch("/api/auth/sign-out", { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); router.push("/sign-in"); }
  async function addPrompt(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/prompts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text: prompt }) }); if (response.ok) { setPrompt(""); router.refresh(); } else setMessage("Could not save prompt."); }
  async function deletePrompt(id: string) { const response = await fetch(`/api/prompts/${id}`, { method: "DELETE" }); if (response.ok) router.refresh(); }
  async function restore(id: string) { const response = await fetch(`/api/entries/${id}/restore`, { method: "POST" }); if (response.ok) router.refresh(); else setMessage("Could not restore entry."); }
  async function permanent(id: string) { if (!confirm("Permanently delete this entry and its files? This cannot be undone.")) return; const response = await fetch(`/api/entries/${id}/permanent`, { method: "DELETE" }); if (response.ok) router.refresh(); else setMessage("Could not permanently delete entry."); }
  return <div className="stack" style={{ gap: 25 }}><section className="panel stack"><h2>Appearance</h2><label>Theme<select value={theme} onChange={event => chooseTheme(event.target.value)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label></section><section className="panel stack"><h2>Your data</h2><p className="muted">Download your journal as structured JSON or readable Markdown. Files are available from individual entries.</p><div className="row"><a className="button" href="/api/exports?format=json">Export JSON</a><a className="button" href="/api/exports?format=markdown">Export Markdown</a></div></section><section className="panel stack"><h2>Your prompts</h2><form className="row" onSubmit={addPrompt}><input value={prompt} onChange={event => setPrompt(event.target.value)} placeholder="A question worth returning to…" required maxLength={500} /><button className="button">Add</button></form>{prompts.map(item => <div className="between" key={item.id}><span>{item.text}</span><button className="text-button" onClick={() => void deletePrompt(item.id)}>Delete</button></div>)}</section><section className="panel stack"><h2>Trash</h2>{trashed.length ? trashed.map(item => <div className="between" key={item.id}><span>{item.title || "Untitled entry"} · {item.local_date}</span><div className="row"><button className="button" onClick={() => void restore(item.id)}>Restore</button><button className="button danger" onClick={() => void permanent(item.id)}>Delete forever</button></div></div>) : <p className="muted">Trash is empty.</p>}</section><section className="panel stack"><h2>Account</h2><p className="muted">Signed in as {email}</p><button className="button" style={{ justifySelf: "start" }} onClick={() => void signOut()}>Sign out</button></section>{message && <p role="alert" className="form-message">{message}</p>}</div>;
}
